import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Union from "../components/UnionMain/Union";
import MobileDetect from "mobile-detect";
import {isMobile} from "react-device-detect";

function Home({ isMobile }) {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Union isMobile={isMobile}/>
        </div>
    )
}

Home.getInitialProps = async (ctx) => {

}

export default Home;